name = "aircraft-registration-lookup"
compatibility_date = "2023-12-01"
compatibility_flags = ["nodejs_compat"]

# Pages specific configuration
pages_build_output_dir = "build"

# Configure environment variables
# These are placeholder values that will be overridden by the values set in the Cloudflare Pages dashboard
[vars]
RAPIDAPI_KEY = "placeholder"
FLIGHTAWARE_API_KEY = "placeholder"
