name = "aircraft-registration-lookup"
compatibility_date = "2023-12-01"
compatibility_flags = ["nodejs_compat"]

# Pages specific configuration
pages_build_output_dir = "build"

# Configure Functions
[functions]
directory = "functions"
