name = "aircraft-registration-lookup"
compatibility_date = "2023-12-01"
compatibility_flags = ["nodejs_compat"]

# Configure Cloudflare Pages
[site]
bucket = "./build"
entry-point = "."

# Configure build command
[build]
command = "npm run build"
output_dir = "build"

# Configure environment variables
[vars]
NODE_VERSION = "18"

# Pages specific configuration
pages_build_output_dir = "build"

# Configure Functions
[functions]
directory = "functions"

# Configure routes
[[routes]]
pattern = "/api/*"
zone_name = "aircraft-registration-lookup.pages.dev"

# Configure dev environment
[dev]
port = 8788
