name = "aircraft-registration-lookup"
compatibility_date = "2023-12-01"

# Configure Cloudflare Pages
[site]
bucket = "./build"
entry-point = "."

# Configure build command
[build]
command = "npm run build"
output_dir = "build"

# Configure environment variables
[vars]
NODE_VERSION = "18"

# Pages specific configuration
pages_build_output_dir = "build"

# Configure routes
[routes]
pattern = "/api/*"
script = "functions/api/[[path]].js"

# Configure dev environment
[dev]
port = 8788
