name = "aircraft-registration-lookup"
compatibility_date = "2023-12-01"
compatibility_flags = ["nodejs_compat"]

# Pages specific configuration
pages_build_output_dir = "build"

# Configure environment variables
# Environment variables are set in the Cloudflare Pages dashboard
# Do not define them here to avoid conflicts
# RAPIDAPI_KEY and FLIGHTAWARE_API_KEY should be set in the Cloudflare Pages dashboard
